local STRINGS = GLOBAL.STRINGS

-- Strings for items and the character
STRINGS.CHARACTER_TITLES.waroline = "The Artist"
STRINGS.CHARACTER_NAMES.waroline = "Waroline"
STRINGS.CHARACTER_DESCRIPTIONS.waroline = "*Brings her lovely sketchbook\n*Allergic to corn\n*Slow eater"
STRINGS.CHARACTER_QUOTES.waroline = "\"The pencil is mightier than the sword!\""

STRINGS.CHARACTER_SURVIVABILITY.waroline = "Slim"
STRINGS.CHARACTERS.WAROLINE = require "speech_waroline"

STRINGS.NAMES.WAROLINE = "Waroline"

STRINGS.SKIN_NAMES.waroline_none = "Basic"
STRINGS.SKIN_DESCRIPTIONS.waroline_none = "Regular look of Waroline, the artist."
STRINGS.SKIN_QUOTES.waroline_none = "The pencil is mightier than the sword!"

STRINGS.SKIN_NAMES.waroline_survivor = "Survivor"
STRINGS.SKIN_DESCRIPTIONS.waroline_survivor = "Waroline after a few months in the Constant."
STRINGS.SKIN_QUOTES.waroline_survivor = "My senses got sharper, as well as my art!"

STRINGS.SKIN_NAMES.waroline_winter = "Wintery"
STRINGS.SKIN_DESCRIPTIONS.waroline_winter = "It might be cold and snowy, but she's prepared for everything."
STRINGS.SKIN_QUOTES.waroline_winter = "I'm not going to get sick while wearing this."

STRINGS.UI.CRAFTING.NEEDSRABBIT_DRAWING 	= "Find a wild Rabbit to draw it!"
STRINGS.UI.CRAFTING.NEEDSSPIDER_DRAWING 	= "Find a wild Spider to draw it!"
STRINGS.UI.CRAFTING.NEEDSSMALLBIRD_DRAWING 	= "Find a wild Tallbird to draw it!"
STRINGS.UI.CRAFTING.NEEDSPIGMAN_DRAWING 	= "Find a wild Pigman to draw it!"
STRINGS.UI.CRAFTING.NEEDSBEEFALO_DRAWING	= "Find a wild Beefalo to draw it!"
STRINGS.UI.CRAFTING.NEEDSKOALEFANT_DRAWING 	= "Find a wild Koalefant to draw it!"
STRINGS.UI.CRAFTING.NEEDSMONKEY_DRAWING 	= "Find a wild Splumonkey to draw it!"

STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "It's too tame and soft to even need a saddle."
STRINGS.CHARACTERS.WILLOW.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "How am I gonna put a saddle on paper??"
STRINGS.CHARACTERS.WOLFGANG.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "Paper hair-cow don't need saddle."
STRINGS.CHARACTERS.WENDY.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "It doesn't abide to the rules of our world."
STRINGS.CHARACTERS.WX78.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 			= "CREATURE'S MOUNTABLE COMPONENT IS ALREADY ENABLED"
STRINGS.CHARACTERS.WICKERBOTTOM.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 	= "Its two-dimensional state deems it exempt from three-dimensional objects."
STRINGS.CHARACTERS.WOODIE.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "How would that even work?"
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "That was foolish to even attempt."
STRINGS.CHARACTERS.WATHGRITHR.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 	= "He's already prepared for battle!"
STRINGS.CHARACTERS.WEBBER.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "We can't put the saddle on him."
STRINGS.CHARACTERS.WINONA.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "That big lug doesn't need a saddle."
STRINGS.CHARACTERS.WARLY.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "Oh non, that's not necessary for this one."
STRINGS.CHARACTERS.WORTOX.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "That's just silly to even think."
STRINGS.CHARACTERS.WORMWOOD.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "Nope"
STRINGS.CHARACTERS.WURT.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 			= "Saddle not work on this."
STRINGS.CHARACTERS.WALTER.ACTIONFAIL.SADDLE.WAROLINE_DRAWING 		= "That one doesn't need a saddle."

STRINGS.NAMES.AXE_DRAWING = "Sketch Axe"
STRINGS.RECIPE_DESC.AXE_DRAWING = "It's drawn to trees."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AXE_DRAWING 	= "A trusty, paper-thin axe." --"Doesn't look very durable."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.AXE_DRAWING 		= "I could burn it or use it to gather things TO burn! Hmm..."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.AXE_DRAWING 	= "Is so light in Wolfgang's mighty hands."
STRINGS.CHARACTERS.WENDY.DESCRIBE.AXE_DRAWING 		= "Once a tree, now an instrument used for cutting more trees. The irony."
STRINGS.CHARACTERS.WX78.DESCRIBE.AXE_DRAWING 		= "CAPABLE OF CAUSING LETHAL PAPERCUTS TO UNSUSPECTING TARGETS"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.AXE_DRAWING= "Quite durable for a paper appliance."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.AXE_DRAWING 		= "It doesn't have the charm that Lucy has."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.AXE_DRAWING 	= "Our new friend's artistic talent may come in handy after all."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.AXE_DRAWING 	= "I'll use it to gather more wood to turn into more paper axes!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.AXE_DRAWING 		= "We love arts and crafts!"	--"My mom and I used to make origami for fun."
STRINGS.CHARACTERS.WINONA.DESCRIBE.AXE_DRAWING 		= "Feels weird to cut down trees with paper."
STRINGS.CHARACTERS.WARLY.DESCRIBE.AXE_DRAWING 		= "Ingenious, non?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.AXE_DRAWING 		= "That mortal is quite good at drawing."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.AXE_DRAWING 	= "Don't want hurt friends with flat friend"
STRINGS.CHARACTERS.WURT.DESCRIBE.AXE_DRAWING 		= "For choppy chop?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.AXE_DRAWING 		= "Seems kinda sketchy to me. Heh, get it?"

STRINGS.NAMES.PICKAXE_DRAWING = "Sketch Pickaxe"
STRINGS.RECIPE_DESC.PICKAXE_DRAWING = "It's drawn to rocks."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PICKAXE_DRAWING		= "Does this thing actually work?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PICKAXE_DRAWING 		= "It may work against rocks, but what about fire?"	--"Paper beats rock!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PICKAXE_DRAWING 	= "Tiny paper thing beat strong rocks?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.PICKAXE_DRAWING 		= "Strange, isn't it, Abigail?"
STRINGS.CHARACTERS.WX78.DESCRIBE.PICKAXE_DRAWING 		= "THE ART FLESHLING IS USEFUL"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PICKAXE_DRAWING= "Works much like a normal pickaxe, but less durable than one."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PICKAXE_DRAWING 		= "It gets the job done."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PICKAXE_DRAWING 	= "It works, I don't know why or how."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PICKAXE_DRAWING 	= "Now my supplies of twigs and flint are saved!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PICKAXE_DRAWING 		= "We love arts and crafts!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.PICKAXE_DRAWING 		= "Huh, who knew paper was this durable?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.PICKAXE_DRAWING 		= "Thank you, mon amie. I'll use it to crack open some stone fruit."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PICKAXE_DRAWING 		= "My paper pickaxe for picking at pebbles and rocks."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PICKAXE_DRAWING 	= "Thin friend is pokey"
STRINGS.CHARACTERS.WURT.DESCRIBE.PICKAXE_DRAWING 		= "Thin paper is for smashing rock."
STRINGS.CHARACTERS.WALTER.DESCRIBE.PICKAXE_DRAWING 		= "Seems kinda sketchy to me. Heh, get it?"

STRINGS.NAMES.CAMPFIRE_DRAWING = "Sketch Campfire"
STRINGS.RECIPE_DESC.CAMPFIRE_DRAWING = "Fluorescent piece of art."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAMPFIRE_DRAWING 		= "It's not a real fire - but the light is real."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAMPFIRE_DRAWING 		= "Boo! The fire isn't even real!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAMPFIRE_DRAWING 		= "Is fire, but not fire. Yes?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAMPFIRE_DRAWING 			= "It glows, but provides me with no respite from the cold."
STRINGS.CHARACTERS.WX78.DESCRIBE.CAMPFIRE_DRAWING 			= "NO THERMAL OUTPUT DETECTED"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAMPFIRE_DRAWING	= "It provides the illusion and glow of a fire, yet gives no warmth."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAMPFIRE_DRAWING 		= "That's a weird one, ain't it, Lucy?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAMPFIRE_DRAWING 		= "It'll help keep Them away, but there's no saving me from the cold."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAMPFIRE_DRAWING 	= "How am I expected to cook the meat of my fallen foes?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAMPFIRE_DRAWING 		= "At least we're safe from the darkness."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAMPFIRE_DRAWING 		= "Phew, thanks for the light, Waroline."
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAMPFIRE_DRAWING 			= "A shame I can't cook with that."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAMPFIRE_DRAWING 		= "It glows bright and shelters from the night, but provides no warmth for delight."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAMPFIRE_DRAWING 		= "Thin friend glows"
STRINGS.CHARACTERS.WURT.DESCRIBE.CAMPFIRE_DRAWING 			= "Paper fire is not warm."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAMPFIRE_DRAWING 		= "I'd best tell my story quickly before the fire goes out."

local sketchbooks = {
	"SKETCHBOOK_WAROLINE",
	"SKETCHBOOK_WAROLINE_SURVIVOR",
	"SKETCHBOOK_WAROLINE_WINTER",
}

STRINGS.SKIN_NAMES.sketchbook_waroline = "Basic"
STRINGS.SKIN_NAMES.sketchbook_waroline_survivor = "Survivor"
STRINGS.SKIN_NAMES.sketchbook_waroline_winter = "Antique"

for k,PREFAB in ipairs(sketchbooks) do
	STRINGS.NAMES[PREFAB] = "Sketchbook"
	STRINGS.RECIPE_DESC[PREFAB] = "Imagination is the only limit."
	
	STRINGS.CHARACTERS.GENERIC.DESCRIBE[PREFAB]	    = "All kinds of ideas for inventions are running wild in my mind!"	--"These blank pages make my imagination run wild!"
	STRINGS.CHARACTERS.WILLOW.DESCRIBE[PREFAB]		= "I'd rather use it as tinder."
	STRINGS.CHARACTERS.WOLFGANG.DESCRIBE[PREFAB]	= "Watch Wolfgang draw mighty circle on little paper."
	STRINGS.CHARACTERS.WENDY.DESCRIBE[PREFAB] 		= "I'm in no mood to draw."
	STRINGS.CHARACTERS.WX78.DESCRIBE[PREFAB] 		= "ERROR: DRAWING.EXE NOT RESPONDING! UNABLE TO COMPLETE ACTION"
	STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE[PREFAB]= "I've never thought about drawing. I might ask Waroline for help."
	STRINGS.CHARACTERS.WOODIE.DESCRIBE[PREFAB] 		= "Aaah, a good use for all that wood."
	STRINGS.CHARACTERS.WAXWELL.DESCRIBE[PREFAB] 	= "Drawing? I have far more pressing matters to attend to."
	STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE[PREFAB] 	= "I'll ask Waroline to draw a portait of myself."
	STRINGS.CHARACTERS.WEBBER.DESCRIBE[PREFAB] 		= "We hope Waroline can teach us how to draw."
	STRINGS.CHARACTERS.WINONA.DESCRIBE[PREFAB] 		= "Hmmm... I could draw a few ideas for machines that have been wandering in my mind."
	STRINGS.CHARACTERS.WARLY.DESCRIBE[PREFAB] 		= "For writing down my grocery list."
	STRINGS.CHARACTERS.WORTOX.DESCRIBE[PREFAB] 		= "A blank page for one to express their inner self."
	STRINGS.CHARACTERS.WORMWOOD.DESCRIBE[PREFAB] 	= "Lots of thin friends"
	STRINGS.CHARACTERS.WURT.DESCRIBE[PREFAB] 		= "Hands are wet, can't draw. Florp..."
	STRINGS.CHARACTERS.WALTER.DESCRIBE[PREFAB] 		= "Should I try drawing Woby?"
end

STRINGS.NAMES.RABBIT_DRAWING = "Sketch Rabbit"
STRINGS.RECIPE_DESC.RABBIT_DRAWING = "A small, fluffy friend."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RABBIT_DRAWING	 	= "He's looking for paper carrots."	--"It's like the real thing, but something feels... off."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.RABBIT_DRAWING 		= "I guess it's kinda cute..."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.RABBIT_DRAWING 	= "Tiny rabbit is made of weak paper."
STRINGS.CHARACTERS.WENDY.DESCRIBE.RABBIT_DRAWING 		= "If it rains then it will surely meet its end."
STRINGS.CHARACTERS.WX78.DESCRIBE.RABBIT_DRAWING 		= "SKETCH OF A DISGUSTING FLESHLING"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.RABBIT_DRAWING	= "A lovely drawing of a Horned Lagormorph."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.RABBIT_DRAWING 		= "I like this one more than the real thing."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.RABBIT_DRAWING 		= "What are we supposed to do with that?"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.RABBIT_DRAWING 	= "It's not made of meat, is it a trick by Loki?!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.RABBIT_DRAWING 		= "We wanna play with the rabbit!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.RABBIT_DRAWING 		= "Good thing it doesn't need to eat or poop."
STRINGS.CHARACTERS.WARLY.DESCRIBE.RABBIT_DRAWING 		= "He's cute, non?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.RABBIT_DRAWING 		= "Always nice to see another hopper, paper or flesh."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.RABBIT_DRAWING 	= "Thin friend is bouncy hopper"
STRINGS.CHARACTERS.WURT.DESCRIBE.RABBIT_DRAWING 		= "Can we keep it?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.RABBIT_DRAWING 		= "Woah, that looks cool!"

STRINGS.NAMES.SPIDER_DRAWING = "Sketch Spider"
STRINGS.RECIPE_DESC.SPIDER_DRAWING = "Friendlier than the original."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDER_DRAWING 		= "It's not as scary as the real thing."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPIDER_DRAWING 		= "At least this one won't try to eat me."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPIDER_DRAWING 	= "I-is good s-spider..."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPIDER_DRAWING 		= "A drawing of a night creature."
STRINGS.CHARACTERS.WX78.DESCRIBE.SPIDER_DRAWING 		= "FRIEND OR FOE?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPIDER_DRAWING	= "A friendly, animate sketch of an arachnid."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPIDER_DRAWING 		= "You could've at least made it look a bit cute."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPIDER_DRAWING 		= "Hopefully it won't turn against us."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPIDER_DRAWING 	= "A horrid companion."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPIDER_DRAWING 		= "We love our new friend!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.SPIDER_DRAWING 		= "I still don't trust it."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SPIDER_DRAWING 		= "He's... charming."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SPIDER_DRAWING 		= "You're cute!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SPIDER_DRAWING 	= "Leggy bug made of thin friend"
STRINGS.CHARACTERS.WURT.DESCRIBE.SPIDER_DRAWING 		= "Good spiderfolk?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.SPIDER_DRAWING 		= "Who's a good spider?"

STRINGS.NAMES.SMALLBIRD_DRAWING = "Sketch Smallbird"
STRINGS.RECIPE_DESC.SMALLBIRD_DRAWING = "This small guy is a big deal."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SMALLBIRD_DRAWING 		= "That's a small piece of paper."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SMALLBIRD_DRAWING 		= "If it was a phoenix, it would burn itself to ashes."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SMALLBIRD_DRAWING 		= "Why is bird so small?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.SMALLBIRD_DRAWING 		= "Welcome to this pitiful world, small one."
STRINGS.CHARACTERS.WX78.DESCRIBE.SMALLBIRD_DRAWING 			= "AT LEAST THIS ONE IS ARTIFICIAL"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SMALLBIRD_DRAWING	= "It's such a cute, small bird."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SMALLBIRD_DRAWING 		= "Aaaah, they are reproducing!!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SMALLBIRD_DRAWING 		= "I'm fine with this one, as long as it stays quiet."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SMALLBIRD_DRAWING 	= "Hide, young 'un. It's not safe out there!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SMALLBIRD_DRAWING 		= "Well, at least this one does not salivate at our sight..."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SMALLBIRD_DRAWING 		= "Come back when you grow up, then we'll talk."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SMALLBIRD_DRAWING 		= "Doesn't seem like this one is edible."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SMALLBIRD_DRAWING 		= "I'm baffled and all, why would you draw a bird this small?"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SMALLBIRD_DRAWING 		= "Small"
STRINGS.CHARACTERS.WURT.DESCRIBE.SMALLBIRD_DRAWING 			= "Is friend."
STRINGS.CHARACTERS.WALTER.DESCRIBE.SMALLBIRD_DRAWING 		= "I wonder if sketches can grow up?"

STRINGS.NAMES.PIGMAN_DRAWING = "Sketch Pigman"
STRINGS.RECIPE_DESC.PIGMAN_DRAWING = "Let him do the heavylifting."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIGMAN_DRAWING 		= "That's some pale pork."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PIGMAN_DRAWING 		= "Good thing this one doesn't smell."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PIGMAN_DRAWING 	= "Ha ha! Pig is made of paper! Wolfgang think is funny!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.PIGMAN_DRAWING 		= "Why would someone want to give life to this creature?"
STRINGS.CHARACTERS.WX78.DESCRIBE.PIGMAN_DRAWING 		= "JUST AS STUPID AS THE REAL ONES"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIGMAN_DRAWING	= "What a lovely drawing, Waroline."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PIGMAN_DRAWING 		= "How does she make it move like that?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PIGMAN_DRAWING 		= "Great, because we didn't have enough of them around."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PIGMAN_DRAWING 		= "My pale ally in battle!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PIGMAN_DRAWING 		= "Friends?"
STRINGS.CHARACTERS.WINONA.DESCRIBE.PIGMAN_DRAWING 		= "It's nice, too bad I can't eat him."
STRINGS.CHARACTERS.WARLY.DESCRIBE.PIGMAN_DRAWING 		= "Maybe he can help me around the kitchen?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PIGMAN_DRAWING 		= "It feels nice to be friends with a pig for once."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PIGMAN_DRAWING 	= "Thin Twirly Tail"
STRINGS.CHARACTERS.WURT.DESCRIBE.PIGMAN_DRAWING 		= "This pigfolk seem good..."
STRINGS.CHARACTERS.WALTER.DESCRIBE.PIGMAN_DRAWING 		= "He's quite slim. Heheh."

-- Only 7 strings max supported!
STRINGS.PIGDRAWING_TALK_ARTIST = {
	"MASTER IS BEST",
	"WHAT WE DO NOW?",
	"IS NICE DAY",
	"NEED HELP?",
	"IS GOOD TIME",
	"MASTER IS GOOD",
	"I FOLLOW",
}

STRINGS.PIGDRAWING_TALK_SCARYFIRE = {
	"FIRE SCARY",
	"AAAAHH!",
	"NO LIKE FIRE",
	"FIRE BAD",
}

STRINGS.NAMES.BEEFALO_DRAWING = "Sketch Beefalo"
STRINGS.RECIPE_DESC.BEEFALO_DRAWING = "A big rideable fluffball."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEFALO_DRAWING 	= "It doesn't poop. I'm not sure if that's for worse or for the better."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEEFALO_DRAWING 		= "Does it drop paper poop?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEEFALO_DRAWING 	= "Hair-cow thing looks different..."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEEFALO_DRAWING 		= "It has the same lifeless stare like the other ones."
STRINGS.CHARACTERS.WX78.DESCRIBE.BEEFALO_DRAWING 		= "STENCH-FREE. GOOD"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEEFALO_DRAWING= "It appears domesticated, I could probably ride it."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEEFALO_DRAWING 		= "I kinda miss the feeling of fur from the real ones."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEEFALO_DRAWING 	= "At least I get to avoid the disgusting smell of manure and wet beefalo fur."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEEFALO_DRAWING 	= "My steed draped in armor of paper."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEEFALO_DRAWING 		= "Big paper beefalo!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.BEEFALO_DRAWING 		= "You're looking kinda thin. Hah!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BEEFALO_DRAWING 		= "No beef here, sadly."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BEEFALO_DRAWING 		= "Have you seen a ghost? You look a bit pale. Hyuyu!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BEEFALO_DRAWING 	= "Thin Shaggy Buddy"
STRINGS.CHARACTERS.WURT.DESCRIBE.BEEFALO_DRAWING 		= "Big fuzzy is made of paper."
STRINGS.CHARACTERS.WALTER.DESCRIBE.BEEFALO_DRAWING 		= "He's become best friends with Woby already!"

STRINGS.NAMES.KOALEFANT_DRAWING = "Sketch Koalefant"
STRINGS.RECIPE_DESC.KOALEFANT_DRAWING = "Adorable and rideable."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KOALEFANT_DRAWING 		= "This one is quite obedient."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.KOALEFANT_DRAWING 		= "Aaw, it's not fuzzy like the real one."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KOALEFANT_DRAWING 		= "If nose is made of paper are there paper boogers?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.KOALEFANT_DRAWING 		= "It wonders aimlessly awaiting its death by the moisture of rain."
STRINGS.CHARACTERS.WX78.DESCRIBE.KOALEFANT_DRAWING 			= "THE FLESHLING DID A DECENT JOB"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KOALEFANT_DRAWING	= "A nicely drawn depiction of a Koalefanta Proboscidea."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.KOALEFANT_DRAWING 		= "You're a big one, eh!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KOALEFANT_DRAWING 		= "She struggled getting the beast to settle down, but she did an overall good job."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KOALEFANT_DRAWING 		= "I shall finally have my own Koalefant steed ready for battle!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.KOALEFANT_DRAWING 		= "This one is our favorite of Waroline's sketches."
STRINGS.CHARACTERS.WINONA.DESCRIBE.KOALEFANT_DRAWING 		= "That must've taken a lot of paper to draw."
STRINGS.CHARACTERS.WARLY.DESCRIBE.KOALEFANT_DRAWING 		= "It looks so pudgy! Too bad we can't eat it."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.KOALEFANT_DRAWING 		= "It was fun watching the mortal run around trying to draw the creature! Hyuyu!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.KOALEFANT_DRAWING 		= "Thin friend go Bruamp!"
STRINGS.CHARACTERS.WURT.DESCRIBE.KOALEFANT_DRAWING 			= "Big animal is cute!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.KOALEFANT_DRAWING 		= "Woby and I can ride it together!"

STRINGS.NAMES.MONKEY_DRAWING = "Sketch Splumonkey"
STRINGS.RECIPE_DESC.MONKEY_DRAWING = "Creepy gnaw-like teeth excluded."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEY_DRAWING 		= "Such a smart little creature."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONKEY_DRAWING 		= "You better not think about flinging poop at me!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONKEY_DRAWING 	= "Monkey man help Wolfgang fetch sticks and grass."
STRINGS.CHARACTERS.WENDY.DESCRIBE.MONKEY_DRAWING 		= "Unintelligent, but helpful."
STRINGS.CHARACTERS.WX78.DESCRIBE.MONKEY_DRAWING 		= "GO GET MY STUFF, FLESHLING"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONKEY_DRAWING	= "He's very kind at helping me gather resources."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONKEY_DRAWING 		= "A hyperactive little guy, eh?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONKEY_DRAWING 		= "She manages to find inspiration in the most drab of creatures."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONKEY_DRAWING 		= "He shall help me gather all matters of materials."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONKEY_DRAWING 		= "He's fast!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.MONKEY_DRAWING 		= "Now no monkey business, y'hear?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.MONKEY_DRAWING 		= "He seems eager to help, how nice."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.MONKEY_DRAWING 		= "He's not a troublemaker like his other friends."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MONKEY_DRAWING 	= "Thin friend help gather stuff"
STRINGS.CHARACTERS.WURT.DESCRIBE.MONKEY_DRAWING 		= "Nice monkey helps me."
STRINGS.CHARACTERS.WALTER.DESCRIBE.MONKEY_DRAWING 		= "Monkey see, monkey do."
